language: python
python:
- '2.7'
- '3.6'
- '3.7'

script: python -m unittest discover -v

# For Python 3.7 support:
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
dist: xenial
sudo: required
